import Button from '@/components/Button';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { routes } from '@/utils/constants';
import { Providers } from './providers';
import NavigationHeader from '@/components/NavigationHeader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavigationHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
}
